# Generated by Django 3.2.5 on 2021-07-07 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='usuario',
            new_name='user',
        ),
    ]
