# Generated by Django 3.2.5 on 2021-07-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_usuario_carrito_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorias',
            old_name='slug',
            new_name='id_cat',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='slug',
            new_name='sku',
        ),
        migrations.AddField(
            model_name='productos',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterIndexTogether(
            name='productos',
            index_together={('id', 'sku')},
        ),
    ]
